#!/usr/bin/env python3
"""Write source/DebugConfig.mc from environment variables.

Monkey C has no preprocessor and no `-D` build define, and a watch app has no
process environment to read at runtime. The only way a build-time switch reaches
the code is as source, so the Makefile generates that source from env and the
compiler sees ordinary constants.

    DEBUG_FORCE_ACTION=walk make run
    make run DEBUG_INSTANT_BATTLE=1 DEBUG_BATTLE_ENEMY=twinflare

Unset means off, so a plain `make build` is always a clean build. `--off`
ignores the environment entirely and is what release and package use, so a
debug switch cannot ride into a store bundle just because it was left exported
in a shell.

The generated file is committed in its all-off form. Without that, building
with monkeyc directly -- no make -- would fail on a missing file.

    python3 tools/debug/gen_debug_config.py [--off] [--check] [--quiet]
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
TARGET = os.path.join(REPO, "source", "DebugConfig.mc")

#! Action names accepted by DEBUG_FORCE_ACTION.
#!
#! The numbers are slot indices, and they have to keep matching both
#! Sprites.ACTION_* and the VARIANTS order in tools/sprites/generate_sprites.py.
#! They are written as bare integers rather than as Sprites.ACTION_* because
#! DebugConfig is (:background) and Sprites, which draws, is not -- referencing
#! it would drag the whole UI layer into background scope.
ACTIONS = {
    "idle": 0,
    "sleep": 1,
    "walk": 2,
    "fight": 3,
    "run": 4,
}

TRUE = ("1", "true", "yes", "on", "y")
FALSE = ("", "0", "false", "no", "off", "n")


class ConfigError(Exception):
    pass


def flag(name):
    raw = os.environ.get(name, "").strip().lower()
    if raw in TRUE:
        return True
    if raw in FALSE:
        return False
    raise ConfigError("%s: expected a boolean, got %r" % (name, raw))


def number(name, default, minimum=0):
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    try:
        value = int(raw)
    except ValueError:
        raise ConfigError("%s: expected an integer, got %r" % (name, raw))
    if value < minimum:
        raise ConfigError("%s: must be >= %d, got %d" % (name, minimum, value))
    return value


def action(name):
    raw = os.environ.get(name, "").strip().lower()
    if not raw:
        return -1
    if raw in ACTIONS:
        return ACTIONS[raw]
    # Accept the raw slot number too, so a new action works before this table does.
    try:
        value = int(raw)
    except ValueError:
        raise ConfigError("%s: expected one of %s, got %r"
                          % (name, ", ".join(sorted(ACTIONS)), raw))
    if value < -1:
        raise ConfigError("%s: must be -1 or a slot index, got %d" % (name, value))
    return value


def settings(off):
    if off:
        return {
            "INSTANT_BATTLE": False,
            "BATTLE_ENEMY": "glacierjaw",
            "BATTLE_IS_BOSS": False,
            "EVENT_GAP": 0,
            "FORCE_ACTION": -1,
        }
    return {
        "INSTANT_BATTLE": flag("DEBUG_INSTANT_BATTLE"),
        "BATTLE_ENEMY": os.environ.get("DEBUG_BATTLE_ENEMY", "").strip() or "glacierjaw",
        "BATTLE_IS_BOSS": flag("DEBUG_BATTLE_IS_BOSS"),
        "EVENT_GAP": number("DEBUG_EVENT_GAP", 0),
        "FORCE_ACTION": action("DEBUG_FORCE_ACTION"),
    }


def mc(name):
    return "true" if name else "false"


def render(s):
    if any(c in s["BATTLE_ENEMY"] for c in '"\\'):
        raise ConfigError("DEBUG_BATTLE_ENEMY: quotes and backslashes are not allowed")

    return '''import Toybox.Lang;

//! Build-time debug switches, generated by tools/debug/gen_debug_config.py.
//!
//! Do not edit: set the environment variables and rebuild. See DEBUG.md.
//!
//!     DEBUG_FORCE_ACTION=walk make run
//!     make run DEBUG_INSTANT_BATTLE=1 DEBUG_BATTLE_ENEMY=twinflare
//!
//! Committed in its all-off form so that building with monkeyc directly, without
//! make, still compiles. `make release` and `make package` regenerate it with
//! --off first, so no switch can reach a store bundle from a stale shell export.
//!
//! Background-scoped because Journey reads EVENT_GAP while the app is closed.
(:background)
module DebugConfig {

    //! Launch straight into a battle instead of the pager. The fight pays out
    //! nothing -- see Encounter.preview.
    const INSTANT_BATTLE = %(instant)s;

    //! Species fought in that battle. An unknown key falls back to a roll.
    const BATTLE_ENEMY = "%(enemy)s";

    //! Show that battle as an area guardian.
    const BATTLE_IS_BOSS = %(boss)s;

    //! Steps between trek events. 0 keeps the real 300/400/500 pacing.
    const EVENT_GAP = %(gap)d;

    //! Pin every creature to one Sprites.ACTION_* pose. -1 lets the pedometer decide.
    const FORCE_ACTION = %(force)d;

    //! True when anything above is on. Views can surface a marker so a debug
    //! build is never mistaken for a real one.
    const ANY = %(any)s;
}
''' % {
        "instant": mc(s["INSTANT_BATTLE"]),
        "enemy": s["BATTLE_ENEMY"],
        "boss": mc(s["BATTLE_IS_BOSS"]),
        "gap": s["EVENT_GAP"],
        "force": s["FORCE_ACTION"],
        "any": mc(s["INSTANT_BATTLE"] or s["BATTLE_IS_BOSS"]
                  or s["EVENT_GAP"] > 0 or s["FORCE_ACTION"] >= 0),
    }


def summary(s):
    on = []
    if s["INSTANT_BATTLE"]:
        on.append("instant-battle=%s%s"
                  % (s["BATTLE_ENEMY"], " (boss)" if s["BATTLE_IS_BOSS"] else ""))
    if s["EVENT_GAP"] > 0:
        on.append("event-gap=%d" % s["EVENT_GAP"])
    if s["FORCE_ACTION"] >= 0:
        names = dict((v, k) for k, v in ACTIONS.items())
        on.append("force-action=%s" % names.get(s["FORCE_ACTION"], s["FORCE_ACTION"]))
    return ", ".join(on) if on else "all off"


def main(argv):
    args = argv[1:]
    off = "--off" in args
    check = "--check" in args
    quiet = "--quiet" in args

    try:
        s = settings(off)
        text = render(s)
    except ConfigError as e:
        sys.stderr.write("debug config: %s\n" % e)
        return 2

    current = None
    if os.path.exists(TARGET):
        with open(TARGET) as f:
            current = f.read()

    if check:
        if current != text:
            sys.stderr.write("debug config: source/DebugConfig.mc is stale\n")
            return 1
        if not quiet:
            print("debug: %s" % summary(s))
        return 0

    # Only rewrite on a real change, so an unchanged config does not touch the
    # file's mtime and force the compiler to redo work.
    if current != text:
        with open(TARGET, "w") as f:
            f.write(text)

    if not quiet:
        print("debug: %s" % summary(s))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
