import Toybox.Lang;
import Toybox.WatchUi;

//! Species key -> drawable ids, generated by tools/sprites/generate_sprites.py.
//!
//! Do not edit: rerun the generator. Each species maps to one array of slots, where
//! the first four are the ACTION_* values in order and the last is the left-facing
//! lunge. A slot's bitmap holds all of its frames stacked, so Sprites clips to the
//! slice it wants. Flat rather than nested because this table is
//! built lazily on a watch and an array of ids is the cheapest shape that works.
module SpriteIndex {

    function build() as Dictionary<String, Array<ResourceId> > {
        return {
            "emberling" => [
                Rez.Drawables.EmberlingIdle, Rez.Drawables.EmberlingSleep, Rez.Drawables.EmberlingMove, Rez.Drawables.EmberlingFight,
                Rez.Drawables.EmberlingFightLeft
            ],
            "drizzlet" => [
                Rez.Drawables.DrizzletIdle, Rez.Drawables.DrizzletSleep, Rez.Drawables.DrizzletMove, Rez.Drawables.DrizzletFight,
                Rez.Drawables.DrizzletFightLeft
            ],
            "sparkmite" => [
                Rez.Drawables.SparkmiteIdle, Rez.Drawables.SparkmiteSleep, Rez.Drawables.SparkmiteMove, Rez.Drawables.SparkmiteFight,
                Rez.Drawables.SparkmiteFightLeft
            ],
            "mosscub" => [
                Rez.Drawables.MosscubIdle, Rez.Drawables.MosscubSleep, Rez.Drawables.MosscubMove, Rez.Drawables.MosscubFight,
                Rez.Drawables.MosscubFightLeft
            ],
            "gustling" => [
                Rez.Drawables.GustlingIdle, Rez.Drawables.GustlingSleep, Rez.Drawables.GustlingMove, Rez.Drawables.GustlingFight,
                Rez.Drawables.GustlingFightLeft
            ],
            "shardpup" => [
                Rez.Drawables.ShardpupIdle, Rez.Drawables.ShardpupSleep, Rez.Drawables.ShardpupMove, Rez.Drawables.ShardpupFight,
                Rez.Drawables.ShardpupFightLeft
            ],
            "cinderpip" => [
                Rez.Drawables.CinderpipIdle, Rez.Drawables.CinderpipSleep, Rez.Drawables.CinderpipMove, Rez.Drawables.CinderpipFight,
                Rez.Drawables.CinderpipFightLeft
            ],
            "silthatch" => [
                Rez.Drawables.SilthatchIdle, Rez.Drawables.SilthatchSleep, Rez.Drawables.SilthatchMove, Rez.Drawables.SilthatchFight,
                Rez.Drawables.SilthatchFightLeft
            ],
            "cinderfang" => [
                Rez.Drawables.CinderfangIdle, Rez.Drawables.CinderfangSleep, Rez.Drawables.CinderfangMove, Rez.Drawables.CinderfangFight,
                Rez.Drawables.CinderfangFightLeft
            ],
            "tidecaller" => [
                Rez.Drawables.TidecallerIdle, Rez.Drawables.TidecallerSleep, Rez.Drawables.TidecallerMove, Rez.Drawables.TidecallerFight,
                Rez.Drawables.TidecallerFightLeft
            ],
            "voltcrest" => [
                Rez.Drawables.VoltcrestIdle, Rez.Drawables.VoltcrestSleep, Rez.Drawables.VoltcrestMove, Rez.Drawables.VoltcrestFight,
                Rez.Drawables.VoltcrestFightLeft
            ],
            "thornmane" => [
                Rez.Drawables.ThornmaneIdle, Rez.Drawables.ThornmaneSleep, Rez.Drawables.ThornmaneMove, Rez.Drawables.ThornmaneFight,
                Rez.Drawables.ThornmaneFightLeft
            ],
            "galewing" => [
                Rez.Drawables.GalewingIdle, Rez.Drawables.GalewingSleep, Rez.Drawables.GalewingMove, Rez.Drawables.GalewingFight,
                Rez.Drawables.GalewingFightLeft
            ],
            "glacierjaw" => [
                Rez.Drawables.GlacierjawIdle, Rez.Drawables.GlacierjawSleep, Rez.Drawables.GlacierjawMove, Rez.Drawables.GlacierjawFight,
                Rez.Drawables.GlacierjawFightLeft
            ],
            "duneshell" => [
                Rez.Drawables.DuneshellIdle, Rez.Drawables.DuneshellSleep, Rez.Drawables.DuneshellMove, Rez.Drawables.DuneshellFight,
                Rez.Drawables.DuneshellFightLeft
            ],
            "ashlynx" => [
                Rez.Drawables.AshlynxIdle, Rez.Drawables.AshlynxSleep, Rez.Drawables.AshlynxMove, Rez.Drawables.AshlynxFight,
                Rez.Drawables.AshlynxFightLeft
            ],
            "pyrewarden" => [
                Rez.Drawables.PyrewardenIdle, Rez.Drawables.PyrewardenSleep, Rez.Drawables.PyrewardenMove, Rez.Drawables.PyrewardenFight,
                Rez.Drawables.PyrewardenFightLeft
            ],
            "abyssward" => [
                Rez.Drawables.AbysswardIdle, Rez.Drawables.AbysswardSleep, Rez.Drawables.AbysswardMove, Rez.Drawables.AbysswardFight,
                Rez.Drawables.AbysswardFightLeft
            ],
            "stormcrown" => [
                Rez.Drawables.StormcrownIdle, Rez.Drawables.StormcrownSleep, Rez.Drawables.StormcrownMove, Rez.Drawables.StormcrownFight,
                Rez.Drawables.StormcrownFightLeft
            ],
            "grovekeeper" => [
                Rez.Drawables.GrovekeeperIdle, Rez.Drawables.GrovekeeperSleep, Rez.Drawables.GrovekeeperMove, Rez.Drawables.GrovekeeperFight,
                Rez.Drawables.GrovekeeperFightLeft
            ],
            "sandmonarch" => [
                Rez.Drawables.SandmonarchIdle, Rez.Drawables.SandmonarchSleep, Rez.Drawables.SandmonarchMove, Rez.Drawables.SandmonarchFight,
                Rez.Drawables.SandmonarchFightLeft
            ],
            "emberdrake" => [
                Rez.Drawables.EmberdrakeIdle, Rez.Drawables.EmberdrakeSleep, Rez.Drawables.EmberdrakeMove, Rez.Drawables.EmberdrakeFight,
                Rez.Drawables.EmberdrakeFightLeft
            ],
            "solmonarch" => [
                Rez.Drawables.SolmonarchIdle, Rez.Drawables.SolmonarchSleep, Rez.Drawables.SolmonarchMove, Rez.Drawables.SolmonarchFight,
                Rez.Drawables.SolmonarchFightLeft
            ],
            "voidsentinel" => [
                Rez.Drawables.VoidsentinelIdle, Rez.Drawables.VoidsentinelSleep, Rez.Drawables.VoidsentinelMove, Rez.Drawables.VoidsentinelFight,
                Rez.Drawables.VoidsentinelFightLeft
            ],
            "flarewisp" => [
                Rez.Drawables.FlarewispIdle, Rez.Drawables.FlarewispSleep, Rez.Drawables.FlarewispMove, Rez.Drawables.FlarewispFight,
                Rez.Drawables.FlarewispFightLeft
            ],
            "stonefang" => [
                Rez.Drawables.StonefangIdle, Rez.Drawables.StonefangSleep, Rez.Drawables.StonefangMove, Rez.Drawables.StonefangFight,
                Rez.Drawables.StonefangFightLeft
            ],
            "twinflare" => [
                Rez.Drawables.TwinflareIdle, Rez.Drawables.TwinflareSleep, Rez.Drawables.TwinflareMove, Rez.Drawables.TwinflareFight,
                Rez.Drawables.TwinflareFightLeft
            ],
            "elderflame" => [
                Rez.Drawables.ElderflameIdle, Rez.Drawables.ElderflameSleep, Rez.Drawables.ElderflameMove, Rez.Drawables.ElderflameFight,
                Rez.Drawables.ElderflameFightLeft
            ],
            "gleammote" => [
                Rez.Drawables.GleammoteIdle, Rez.Drawables.GleammoteSleep, Rez.Drawables.GleammoteMove, Rez.Drawables.GleammoteFight,
                Rez.Drawables.GleammoteFightLeft
            ]
        };
    }

    //! Frames in one species' variant, when it is not the usual two.
    //!
    //! An if-chain over just the exceptions rather than a table: almost every variant is
    //! two frames, so the common answer should cost no allocation and no lookup. Hand-drawn
    //! overrides are the only source of anything else.
    function frameCount(key as String, slot as Number) as Number {
        if (slot == 0 && key.equals("emberling")) { return 4; }
        if (slot == 2 && key.equals("emberling")) { return 4; }
        if (slot == 1 && key.equals("emberling")) { return 3; }
        return 2;
    }
}
