import Toybox.Lang;
import Toybox.WatchUi;

//! Species key -> drawable ids, generated by tools/sprites/generate_sprites.py.
//!
//! Do not edit: rerun the generator. Each species maps to one array of slots in
//! ACTION_* order, each directional action followed by its left-facing mirror. A slot
//! is null when the species has no art for it, which is how the hand-drawn attack
//! poses stay off the drawable budget of the species that do not have them --
//! Sprites falls back to the fight stance there. A slot's bitmap holds all of its
//! frames stacked, so Sprites clips to the slice it wants. Flat rather than nested
//! because this table is built lazily on a watch and an array of ids is the cheapest
//! shape that works.
module SpriteIndex {

    function build() as Dictionary<String, Array<ResourceId?> > {
        return {
            "nonce" => [
                Rez.Drawables.NonceIdle, Rez.Drawables.NonceSleep, Rez.Drawables.NonceMove, Rez.Drawables.NonceFight,
                Rez.Drawables.NonceFightLeft, null, null, null,
                null, null, null
            ],
            "drizzlet" => [
                Rez.Drawables.DrizzletIdle, Rez.Drawables.DrizzletSleep, Rez.Drawables.DrizzletMove, Rez.Drawables.DrizzletFight,
                Rez.Drawables.DrizzletFightLeft, null, null, null,
                null, null, null
            ],
            "sparkmite" => [
                Rez.Drawables.SparkmiteIdle, Rez.Drawables.SparkmiteSleep, Rez.Drawables.SparkmiteMove, Rez.Drawables.SparkmiteFight,
                Rez.Drawables.SparkmiteFightLeft, null, null, null,
                null, null, null
            ],
            "mosscub" => [
                Rez.Drawables.MosscubIdle, Rez.Drawables.MosscubSleep, Rez.Drawables.MosscubMove, Rez.Drawables.MosscubFight,
                Rez.Drawables.MosscubFightLeft, null, null, null,
                null, null, null
            ],
            "gustling" => [
                Rez.Drawables.GustlingIdle, Rez.Drawables.GustlingSleep, Rez.Drawables.GustlingMove, Rez.Drawables.GustlingFight,
                Rez.Drawables.GustlingFightLeft, null, null, null,
                null, null, null
            ],
            "shardpup" => [
                Rez.Drawables.ShardpupIdle, Rez.Drawables.ShardpupSleep, Rez.Drawables.ShardpupMove, Rez.Drawables.ShardpupFight,
                Rez.Drawables.ShardpupFightLeft, null, null, null,
                null, null, null
            ],
            "cinderpip" => [
                Rez.Drawables.CinderpipIdle, Rez.Drawables.CinderpipSleep, Rez.Drawables.CinderpipMove, Rez.Drawables.CinderpipFight,
                Rez.Drawables.CinderpipFightLeft, null, null, null,
                null, null, null
            ],
            "silthatch" => [
                Rez.Drawables.SilthatchIdle, Rez.Drawables.SilthatchSleep, Rez.Drawables.SilthatchMove, Rez.Drawables.SilthatchFight,
                Rez.Drawables.SilthatchFightLeft, null, null, null,
                null, null, null
            ],
            "cinderfang" => [
                Rez.Drawables.CinderfangIdle, Rez.Drawables.CinderfangSleep, Rez.Drawables.CinderfangMove, Rez.Drawables.CinderfangFight,
                Rez.Drawables.CinderfangFightLeft, null, null, null,
                null, null, null
            ],
            "tidecaller" => [
                Rez.Drawables.TidecallerIdle, Rez.Drawables.TidecallerSleep, Rez.Drawables.TidecallerMove, Rez.Drawables.TidecallerFight,
                Rez.Drawables.TidecallerFightLeft, null, null, null,
                null, null, null
            ],
            "voltcrest" => [
                Rez.Drawables.VoltcrestIdle, Rez.Drawables.VoltcrestSleep, Rez.Drawables.VoltcrestMove, Rez.Drawables.VoltcrestFight,
                Rez.Drawables.VoltcrestFightLeft, null, null, null,
                null, null, null
            ],
            "thornmane" => [
                Rez.Drawables.ThornmaneIdle, Rez.Drawables.ThornmaneSleep, Rez.Drawables.ThornmaneMove, Rez.Drawables.ThornmaneFight,
                Rez.Drawables.ThornmaneFightLeft, null, null, null,
                null, null, null
            ],
            "galewing" => [
                Rez.Drawables.GalewingIdle, Rez.Drawables.GalewingSleep, Rez.Drawables.GalewingMove, Rez.Drawables.GalewingFight,
                Rez.Drawables.GalewingFightLeft, null, null, null,
                null, null, null
            ],
            "glacierjaw" => [
                Rez.Drawables.GlacierjawIdle, Rez.Drawables.GlacierjawSleep, Rez.Drawables.GlacierjawMove, Rez.Drawables.GlacierjawFight,
                Rez.Drawables.GlacierjawFightLeft, null, null, null,
                null, null, null
            ],
            "duneshell" => [
                Rez.Drawables.DuneshellIdle, Rez.Drawables.DuneshellSleep, Rez.Drawables.DuneshellMove, Rez.Drawables.DuneshellFight,
                Rez.Drawables.DuneshellFightLeft, null, null, null,
                null, null, null
            ],
            "ashlynx" => [
                Rez.Drawables.AshlynxIdle, Rez.Drawables.AshlynxSleep, Rez.Drawables.AshlynxMove, Rez.Drawables.AshlynxFight,
                Rez.Drawables.AshlynxFightLeft, null, null, null,
                null, null, null
            ],
            "pyrewarden" => [
                Rez.Drawables.PyrewardenIdle, Rez.Drawables.PyrewardenSleep, Rez.Drawables.PyrewardenMove, Rez.Drawables.PyrewardenFight,
                Rez.Drawables.PyrewardenFightLeft, null, null, null,
                null, null, null
            ],
            "abyssward" => [
                Rez.Drawables.AbysswardIdle, Rez.Drawables.AbysswardSleep, Rez.Drawables.AbysswardMove, Rez.Drawables.AbysswardFight,
                Rez.Drawables.AbysswardFightLeft, null, null, null,
                null, null, null
            ],
            "stormcrown" => [
                Rez.Drawables.StormcrownIdle, Rez.Drawables.StormcrownSleep, Rez.Drawables.StormcrownMove, Rez.Drawables.StormcrownFight,
                Rez.Drawables.StormcrownFightLeft, null, null, null,
                null, null, null
            ],
            "grovekeeper" => [
                Rez.Drawables.GrovekeeperIdle, Rez.Drawables.GrovekeeperSleep, Rez.Drawables.GrovekeeperMove, Rez.Drawables.GrovekeeperFight,
                Rez.Drawables.GrovekeeperFightLeft, null, null, null,
                null, null, null
            ],
            "sandmonarch" => [
                Rez.Drawables.SandmonarchIdle, Rez.Drawables.SandmonarchSleep, Rez.Drawables.SandmonarchMove, Rez.Drawables.SandmonarchFight,
                Rez.Drawables.SandmonarchFightLeft, null, null, null,
                null, null, null
            ],
            "emberdrake" => [
                Rez.Drawables.EmberdrakeIdle, Rez.Drawables.EmberdrakeSleep, Rez.Drawables.EmberdrakeMove, Rez.Drawables.EmberdrakeFight,
                Rez.Drawables.EmberdrakeFightLeft, null, null, null,
                null, null, null
            ],
            "solmonarch" => [
                Rez.Drawables.SolmonarchIdle, Rez.Drawables.SolmonarchSleep, Rez.Drawables.SolmonarchMove, Rez.Drawables.SolmonarchFight,
                Rez.Drawables.SolmonarchFightLeft, null, null, null,
                null, null, null
            ],
            "voidsentinel" => [
                Rez.Drawables.VoidsentinelIdle, Rez.Drawables.VoidsentinelSleep, Rez.Drawables.VoidsentinelMove, Rez.Drawables.VoidsentinelFight,
                Rez.Drawables.VoidsentinelFightLeft, null, null, null,
                null, null, null
            ],
            "flarewisp" => [
                Rez.Drawables.FlarewispIdle, Rez.Drawables.FlarewispSleep, Rez.Drawables.FlarewispMove, Rez.Drawables.FlarewispFight,
                Rez.Drawables.FlarewispFightLeft, null, null, null,
                null, null, null
            ],
            "stonefang" => [
                Rez.Drawables.StonefangIdle, Rez.Drawables.StonefangSleep, Rez.Drawables.StonefangMove, Rez.Drawables.StonefangFight,
                Rez.Drawables.StonefangFightLeft, null, null, null,
                null, null, null
            ],
            "twinflare" => [
                Rez.Drawables.TwinflareIdle, Rez.Drawables.TwinflareSleep, Rez.Drawables.TwinflareMove, Rez.Drawables.TwinflareFight,
                Rez.Drawables.TwinflareFightLeft, null, null, null,
                null, null, null
            ],
            "elderflame" => [
                Rez.Drawables.ElderflameIdle, Rez.Drawables.ElderflameSleep, Rez.Drawables.ElderflameMove, Rez.Drawables.ElderflameFight,
                Rez.Drawables.ElderflameFightLeft, null, null, null,
                null, null, null
            ],
            "gleammote" => [
                Rez.Drawables.GleammoteIdle, Rez.Drawables.GleammoteSleep, Rez.Drawables.GleammoteMove, Rez.Drawables.GleammoteFight,
                Rez.Drawables.GleammoteFightLeft, null, null, null,
                null, null, null
            ],
            "slime" => [
                Rez.Drawables.SlimeIdle, Rez.Drawables.SlimeSleep, Rez.Drawables.SlimeMove, Rez.Drawables.SlimeFight,
                Rez.Drawables.SlimeFightLeft, Rez.Drawables.SlimeRock, Rez.Drawables.SlimeRockLeft, Rez.Drawables.SlimePaper,
                Rez.Drawables.SlimePaperLeft, Rez.Drawables.SlimeScissors, Rez.Drawables.SlimeScissorsLeft
            ]
        };
    }

    //! Frames in one species' variant, when it is not the usual two.
    //!
    //! An if-chain over just the exceptions rather than a table: almost every variant is
    //! two frames, so the common answer should cost no allocation and no lookup. Hand-drawn
    //! overrides are the only source of anything else.
    function frameCount(key as String, slot as Number) as Number {
        if (slot == 0 && key.equals("nonce")) { return 4; }
        if (slot == 2 && key.equals("nonce")) { return 4; }
        if (slot == 1 && key.equals("nonce")) { return 3; }
        if (slot == 0 && key.equals("slime")) { return 4; }
        if (slot == 2 && key.equals("slime")) { return 4; }
        if (slot == 1 && key.equals("slime")) { return 4; }
        return 2;
    }
}
