import Toybox.Lang;
import Toybox.WatchUi;

//! Species key -> drawable ids, generated by tools/sprites/generate_sprites.py.
//!
//! Do not edit: rerun the generator. Each species maps to one array of slots, where
//! the first five are the ACTION_* values in order and the last two are the
//! left-facing lunge and lean. A slot's bitmap holds all of its frames stacked, so
//! Sprites clips to the slice it wants. Flat rather than nested because this table is
//! built lazily on a watch and an array of ids is the cheapest shape that works.
module SpriteIndex {

    function build() as Dictionary<String, Array<ResourceId> > {
        return {
            "emberling" => [
                Rez.Drawables.EmberlingIdle, Rez.Drawables.EmberlingSleep, Rez.Drawables.EmberlingWalk, Rez.Drawables.EmberlingFight,
                Rez.Drawables.EmberlingRun, Rez.Drawables.EmberlingFightLeft, Rez.Drawables.EmberlingRunLeft
            ],
            "drizzlet" => [
                Rez.Drawables.DrizzletIdle, Rez.Drawables.DrizzletSleep, Rez.Drawables.DrizzletWalk, Rez.Drawables.DrizzletFight,
                Rez.Drawables.DrizzletRun, Rez.Drawables.DrizzletFightLeft, Rez.Drawables.DrizzletRunLeft
            ],
            "sparkmite" => [
                Rez.Drawables.SparkmiteIdle, Rez.Drawables.SparkmiteSleep, Rez.Drawables.SparkmiteWalk, Rez.Drawables.SparkmiteFight,
                Rez.Drawables.SparkmiteRun, Rez.Drawables.SparkmiteFightLeft, Rez.Drawables.SparkmiteRunLeft
            ],
            "mosscub" => [
                Rez.Drawables.MosscubIdle, Rez.Drawables.MosscubSleep, Rez.Drawables.MosscubWalk, Rez.Drawables.MosscubFight,
                Rez.Drawables.MosscubRun, Rez.Drawables.MosscubFightLeft, Rez.Drawables.MosscubRunLeft
            ],
            "gustling" => [
                Rez.Drawables.GustlingIdle, Rez.Drawables.GustlingSleep, Rez.Drawables.GustlingWalk, Rez.Drawables.GustlingFight,
                Rez.Drawables.GustlingRun, Rez.Drawables.GustlingFightLeft, Rez.Drawables.GustlingRunLeft
            ],
            "shardpup" => [
                Rez.Drawables.ShardpupIdle, Rez.Drawables.ShardpupSleep, Rez.Drawables.ShardpupWalk, Rez.Drawables.ShardpupFight,
                Rez.Drawables.ShardpupRun, Rez.Drawables.ShardpupFightLeft, Rez.Drawables.ShardpupRunLeft
            ],
            "cinderpip" => [
                Rez.Drawables.CinderpipIdle, Rez.Drawables.CinderpipSleep, Rez.Drawables.CinderpipWalk, Rez.Drawables.CinderpipFight,
                Rez.Drawables.CinderpipRun, Rez.Drawables.CinderpipFightLeft, Rez.Drawables.CinderpipRunLeft
            ],
            "silthatch" => [
                Rez.Drawables.SilthatchIdle, Rez.Drawables.SilthatchSleep, Rez.Drawables.SilthatchWalk, Rez.Drawables.SilthatchFight,
                Rez.Drawables.SilthatchRun, Rez.Drawables.SilthatchFightLeft, Rez.Drawables.SilthatchRunLeft
            ],
            "cinderfang" => [
                Rez.Drawables.CinderfangIdle, Rez.Drawables.CinderfangSleep, Rez.Drawables.CinderfangWalk, Rez.Drawables.CinderfangFight,
                Rez.Drawables.CinderfangRun, Rez.Drawables.CinderfangFightLeft, Rez.Drawables.CinderfangRunLeft
            ],
            "tidecaller" => [
                Rez.Drawables.TidecallerIdle, Rez.Drawables.TidecallerSleep, Rez.Drawables.TidecallerWalk, Rez.Drawables.TidecallerFight,
                Rez.Drawables.TidecallerRun, Rez.Drawables.TidecallerFightLeft, Rez.Drawables.TidecallerRunLeft
            ],
            "voltcrest" => [
                Rez.Drawables.VoltcrestIdle, Rez.Drawables.VoltcrestSleep, Rez.Drawables.VoltcrestWalk, Rez.Drawables.VoltcrestFight,
                Rez.Drawables.VoltcrestRun, Rez.Drawables.VoltcrestFightLeft, Rez.Drawables.VoltcrestRunLeft
            ],
            "thornmane" => [
                Rez.Drawables.ThornmaneIdle, Rez.Drawables.ThornmaneSleep, Rez.Drawables.ThornmaneWalk, Rez.Drawables.ThornmaneFight,
                Rez.Drawables.ThornmaneRun, Rez.Drawables.ThornmaneFightLeft, Rez.Drawables.ThornmaneRunLeft
            ],
            "galewing" => [
                Rez.Drawables.GalewingIdle, Rez.Drawables.GalewingSleep, Rez.Drawables.GalewingWalk, Rez.Drawables.GalewingFight,
                Rez.Drawables.GalewingRun, Rez.Drawables.GalewingFightLeft, Rez.Drawables.GalewingRunLeft
            ],
            "glacierjaw" => [
                Rez.Drawables.GlacierjawIdle, Rez.Drawables.GlacierjawSleep, Rez.Drawables.GlacierjawWalk, Rez.Drawables.GlacierjawFight,
                Rez.Drawables.GlacierjawRun, Rez.Drawables.GlacierjawFightLeft, Rez.Drawables.GlacierjawRunLeft
            ],
            "duneshell" => [
                Rez.Drawables.DuneshellIdle, Rez.Drawables.DuneshellSleep, Rez.Drawables.DuneshellWalk, Rez.Drawables.DuneshellFight,
                Rez.Drawables.DuneshellRun, Rez.Drawables.DuneshellFightLeft, Rez.Drawables.DuneshellRunLeft
            ],
            "ashlynx" => [
                Rez.Drawables.AshlynxIdle, Rez.Drawables.AshlynxSleep, Rez.Drawables.AshlynxWalk, Rez.Drawables.AshlynxFight,
                Rez.Drawables.AshlynxRun, Rez.Drawables.AshlynxFightLeft, Rez.Drawables.AshlynxRunLeft
            ],
            "pyrewarden" => [
                Rez.Drawables.PyrewardenIdle, Rez.Drawables.PyrewardenSleep, Rez.Drawables.PyrewardenWalk, Rez.Drawables.PyrewardenFight,
                Rez.Drawables.PyrewardenRun, Rez.Drawables.PyrewardenFightLeft, Rez.Drawables.PyrewardenRunLeft
            ],
            "abyssward" => [
                Rez.Drawables.AbysswardIdle, Rez.Drawables.AbysswardSleep, Rez.Drawables.AbysswardWalk, Rez.Drawables.AbysswardFight,
                Rez.Drawables.AbysswardRun, Rez.Drawables.AbysswardFightLeft, Rez.Drawables.AbysswardRunLeft
            ],
            "stormcrown" => [
                Rez.Drawables.StormcrownIdle, Rez.Drawables.StormcrownSleep, Rez.Drawables.StormcrownWalk, Rez.Drawables.StormcrownFight,
                Rez.Drawables.StormcrownRun, Rez.Drawables.StormcrownFightLeft, Rez.Drawables.StormcrownRunLeft
            ],
            "grovekeeper" => [
                Rez.Drawables.GrovekeeperIdle, Rez.Drawables.GrovekeeperSleep, Rez.Drawables.GrovekeeperWalk, Rez.Drawables.GrovekeeperFight,
                Rez.Drawables.GrovekeeperRun, Rez.Drawables.GrovekeeperFightLeft, Rez.Drawables.GrovekeeperRunLeft
            ],
            "sandmonarch" => [
                Rez.Drawables.SandmonarchIdle, Rez.Drawables.SandmonarchSleep, Rez.Drawables.SandmonarchWalk, Rez.Drawables.SandmonarchFight,
                Rez.Drawables.SandmonarchRun, Rez.Drawables.SandmonarchFightLeft, Rez.Drawables.SandmonarchRunLeft
            ],
            "emberdrake" => [
                Rez.Drawables.EmberdrakeIdle, Rez.Drawables.EmberdrakeSleep, Rez.Drawables.EmberdrakeWalk, Rez.Drawables.EmberdrakeFight,
                Rez.Drawables.EmberdrakeRun, Rez.Drawables.EmberdrakeFightLeft, Rez.Drawables.EmberdrakeRunLeft
            ],
            "solmonarch" => [
                Rez.Drawables.SolmonarchIdle, Rez.Drawables.SolmonarchSleep, Rez.Drawables.SolmonarchWalk, Rez.Drawables.SolmonarchFight,
                Rez.Drawables.SolmonarchRun, Rez.Drawables.SolmonarchFightLeft, Rez.Drawables.SolmonarchRunLeft
            ],
            "voidsentinel" => [
                Rez.Drawables.VoidsentinelIdle, Rez.Drawables.VoidsentinelSleep, Rez.Drawables.VoidsentinelWalk, Rez.Drawables.VoidsentinelFight,
                Rez.Drawables.VoidsentinelRun, Rez.Drawables.VoidsentinelFightLeft, Rez.Drawables.VoidsentinelRunLeft
            ],
            "flarewisp" => [
                Rez.Drawables.FlarewispIdle, Rez.Drawables.FlarewispSleep, Rez.Drawables.FlarewispWalk, Rez.Drawables.FlarewispFight,
                Rez.Drawables.FlarewispRun, Rez.Drawables.FlarewispFightLeft, Rez.Drawables.FlarewispRunLeft
            ],
            "stonefang" => [
                Rez.Drawables.StonefangIdle, Rez.Drawables.StonefangSleep, Rez.Drawables.StonefangWalk, Rez.Drawables.StonefangFight,
                Rez.Drawables.StonefangRun, Rez.Drawables.StonefangFightLeft, Rez.Drawables.StonefangRunLeft
            ],
            "twinflare" => [
                Rez.Drawables.TwinflareIdle, Rez.Drawables.TwinflareSleep, Rez.Drawables.TwinflareWalk, Rez.Drawables.TwinflareFight,
                Rez.Drawables.TwinflareRun, Rez.Drawables.TwinflareFightLeft, Rez.Drawables.TwinflareRunLeft
            ],
            "elderflame" => [
                Rez.Drawables.ElderflameIdle, Rez.Drawables.ElderflameSleep, Rez.Drawables.ElderflameWalk, Rez.Drawables.ElderflameFight,
                Rez.Drawables.ElderflameRun, Rez.Drawables.ElderflameFightLeft, Rez.Drawables.ElderflameRunLeft
            ],
            "gleammote" => [
                Rez.Drawables.GleammoteIdle, Rez.Drawables.GleammoteSleep, Rez.Drawables.GleammoteWalk, Rez.Drawables.GleammoteFight,
                Rez.Drawables.GleammoteRun, Rez.Drawables.GleammoteFightLeft, Rez.Drawables.GleammoteRunLeft
            ]
        };
    }

    //! Frames in one species' variant, when it is not the usual two.
    //!
    //! An if-chain over just the exceptions rather than a table: almost every variant is
    //! two frames, so the common answer should cost no allocation and no lookup. Hand-drawn
    //! overrides are the only source of anything else.
    function frameCount(key as String, slot as Number) as Number {
        if (slot == 2 && key.equals("emberling")) { return 4; }
        return 2;
    }
}
