import Toybox.Lang;

//! Build-time debug switches, generated by tools/debug/gen_debug_config.py.
//!
//! Do not edit: set the environment variables and rebuild. See DEBUG.md.
//!
//!     DEBUG_FORCE_ACTION=move make run
//!     make run DEBUG_INSTANT_BATTLE=1 DEBUG_BATTLE_ENEMY=twinflare
//!
//! Committed in its all-off form so that building with monkeyc directly, without
//! make, still compiles. `make release` and `make package` regenerate it with
//! --off first, so no switch can reach a store bundle from a stale shell export.
//!
//! Background-scoped because Journey reads EVENT_GAP while the app is closed.
(:background)
module DebugConfig {

    //! Launch straight into a battle instead of the pager. The fight pays out
    //! nothing -- see Encounter.preview.
    const INSTANT_BATTLE = false;

    //! Species fought in that battle. An unknown key falls back to a roll.
    const BATTLE_ENEMY = "glacierjaw";

    //! Show that battle as an area guardian.
    const BATTLE_IS_BOSS = false;

    //! Steps between trek events. 0 keeps the real 300/400/500 pacing.
    const EVENT_GAP = 0;

    //! Pin every creature to one Sprites.ACTION_* pose. -1 lets the pedometer decide.
    const FORCE_ACTION = -1;

    //! True when anything above is on. Views can surface a marker so a debug
    //! build is never mistaken for a real one.
    const ANY = false;
}
